name: CI/CD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write
  security-events: write

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [quality, build, unit-tests, coverage, security]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        if: matrix.job != 'security'
        with:
          node-version: 22
          package-manager-cache: false

      - name: Enable Corepack
        if: matrix.job != 'security'
        run: corepack enable

      - name: Cache Yarn dependencies
        if: matrix.job != 'security'
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-${{ runner.os }}-

      - name: Install dependencies
        if: matrix.job != 'security'
        run: yarn install --immutable

      - name: Quality checks
        if: matrix.job == 'quality'
        run: yarn quality

      - name: Build
        if: matrix.job == 'build'
        run: yarn build

      - name: Unit tests
        if: matrix.job == 'unit-tests'
        run: yarn test
        timeout-minutes: 10

      - name: Coverage tests
        if: matrix.job == 'coverage'
        run: yarn test:coverage
        timeout-minutes: 15

      - name: Upload Coverage to Codecov
        if: matrix.job == 'coverage'
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false

      - name: Security scan (njsscan)
        if: matrix.job == 'security'
        id: njsscan
        uses: ajinabraham/njsscan-action@231750a435d85095d33be7d192d52ec650625146 # v9
        with:
          args: '. --sarif --output results.sarif || true'

      - name: Upload security scan results
        if: matrix.job == 'security'
        uses: github/codeql-action/upload-sarif@3599b3baa15b485a2e49ef411a7a4bb2452e7f93 # v3
        with:
          sarif_file: results.sarif

  # Playwright E2E测试 - 独立job避免版本冲突
  e2e-tests:
    runs-on: ubuntu-latest
    needs: ci
    if: success()
    
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          package-manager-cache: false

      - name: Enable Corepack
        run: corepack enable

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-${{ runner.os }}-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('yarn.lock', 'package.json') }}
          restore-keys: playwright-${{ runner.os }}-

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: ./scripts/install-playwright.sh

      - name: Build application
        run: yarn build

      - name: Start application and run tests
        run: |
          # 启动应用
          yarn start &
          APP_PID=$!
          
          # 等待应用就绪
          echo "Waiting for application..."
          for i in {1..30}; do
            if curl -f http://localhost:3000/api/health >/dev/null 2>&1; then
              echo "Application ready!"
              break
            fi
            sleep 2
          done
          
          # 运行测试
          yarn playwright test
          TEST_EXIT=$?
          
          # 清理
          kill $APP_PID || true
          exit $TEST_EXIT
        env:
          BASE_URL: http://localhost:3000

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30